# Importing Libraries
import streamlit as st

# App
st.set_page_config(
    page_title="🔍 veTHE Checker",
    page_icon="icons/thena.png",
    layout="wide",
)

# Title
st.title("💬 About")

# Content
st.write(
    """## What is veTHE?
veTHE is 'THE' locked for voting power.

## What is the utility of veTHE?
- Protocol revenue access: veTHE holders can vote for gauges on a weekly basis, and access 80% of the trading fees (later 90%) and 100% of the bribes for the associated pool. 
- Governance participation: veTHE holders can partake in governance and cast votes for the protocol improvement proposals.

## What do veTHE voters receive?
- Trading fees generated by the pool(s) they vote for
- Bribes deposited for the pools they vote for
- Weekly veTHE distribution (rebase)

## Why this Tracker?
This was created by me aka 🍓ALMIGHTY ABE🍓 to fill the gap of NFT marketplaces not showcasing Financial NFTs properly and making veTHE metadata user-friendly.

## Important Links
My Twitter: https://twitter.com/ALM1GHTYABE

Thena's Twitter: [https://twitter.com/ThenaFi_](https://twitter.com/ThenaFi_)

Thena's Discord: https://discord.gg/thena

veTHE Collection: https://opensea.io/collection/vethena

## Note
NFA, DYOR -- This web app is in beta, I am not responsible for any information on this webapp.

If you find any inaccuracies on this webapp feel free to reach out to me on Twitter or in Thena's Discord. 

## If you like this project, you may buy me a cup of coffee ☕ or use my Thena Referral.
"""
)
st.code("0x5783Fb2f3d93364041d49097b66086703527AeaC")
st.code("https://www.thena.fi/referral/?ref=DeezNuts")

st.write("PS: That's actually my referral 🥜")
